// <auto-generated />
public static class KarnivalProtocol
{
    public const ushort Version = 44;
}

public enum NetworkMessageId : ushort
{
    LoginRequest = 1,
    LoginResult = 2,
    MiniGameStarted = 3,
    MiniGameInput = 4,
    MiniGameResults = 5,
    MiniGameScore = 6,
    ChatSend = 7,
    ChatBroadcast = 8,
    MiniGameEvent = 9,
    SessionCountdown = 10,
    SessionLobbyRoster = 11,
    SessionVictory = 12,
    MiniGameReady = 13,
    MiniGameCountdown = 14,
    SessionBettingState = 15,
    SessionBettingUpdate = 16,
    SessionBet = 17,
    SessionWaiting = 18,
}

public enum MiniGameType : ushort
{
    SliderTarget = 1,
    ObstacleRunner = 2,
    PhotoPuzzleSlider = 3,
    FallingObjectCatcher = 4,
    HordeClicker = 5,
    ColorMatch = 6,
    ColorSequence = 7,
    CardMatch = 8,
    CupAndBall = 9,
    CarPark = 10,
    ArcheryPractice = 11,
    StopGo = 12,
    PotatoFace = 13,
    SpotTheDifference = 14,
    PlateStacker = 15,
    Maze = 16,
    SmackMan = 17,
    WheresBaldo = 18,
    WheelSpinner = 19,
    StepIntoTraffic = 20,
}
