using System.Text;
using System.Text.Json;

namespace Karnival.ProtocolGeneration;

public sealed class ProtocolSchema
{
    public ushort Version { get; init; }
    public Dictionary<string, ushort> NetworkMessageIds { get; init; } = new();
    public Dictionary<string, ushort> MiniGameTypes { get; init; } = new();
}

public static class ProtocolCodeGenerator
{
    public static ProtocolSchema ReadSchema(string path)
    {
        ProtocolSchema schema = JsonSerializer.Deserialize<ProtocolSchema>(
            File.ReadAllText(path),
            new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
            ?? throw new InvalidDataException("Protocol schema is empty.");
        Validate(schema);
        return schema;
    }

    public static string Render(ProtocolSchema schema)
    {
        Validate(schema);
        StringBuilder output = new();
        output.AppendLine("// <auto-generated />");
        output.AppendLine("public static class KarnivalProtocol");
        output.AppendLine("{");
        output.AppendLine($"    public const ushort Version = {schema.Version};");
        output.AppendLine("}");
        output.AppendLine();
        AppendEnum(output, "NetworkMessageId", schema.NetworkMessageIds);
        output.AppendLine();
        AppendEnum(output, "MiniGameType", schema.MiniGameTypes);
        return output.ToString().Replace("\r\n", "\n");
    }

    public static bool Matches(string path, string expected)
    {
        return File.Exists(path) &&
            Normalize(File.ReadAllText(path)) == Normalize(expected);
    }

    public static void Write(string path, string content)
    {
        string? directory = Path.GetDirectoryName(Path.GetFullPath(path));
        if (!string.IsNullOrEmpty(directory))
            Directory.CreateDirectory(directory);
        File.WriteAllText(path, Normalize(content), new UTF8Encoding(false));
    }

    private static void AppendEnum(
        StringBuilder output,
        string name,
        IReadOnlyDictionary<string, ushort> values)
    {
        output.AppendLine($"public enum {name} : ushort");
        output.AppendLine("{");
        foreach ((string key, ushort value) in values)
            output.AppendLine($"    {key} = {value},");
        output.AppendLine("}");
    }

    private static void Validate(ProtocolSchema schema)
    {
        if (schema.Version == 0)
            throw new InvalidDataException("Protocol version must be positive.");
        ValidateEnum("networkMessageIds", schema.NetworkMessageIds);
        ValidateEnum("miniGameTypes", schema.MiniGameTypes);
    }

    private static void ValidateEnum(
        string name,
        IReadOnlyDictionary<string, ushort> values)
    {
        if (values.Count == 0)
            throw new InvalidDataException($"{name} must not be empty.");
        if (values.Keys.Any(key => string.IsNullOrWhiteSpace(key)))
            throw new InvalidDataException($"{name} contains an empty name.");
        if (values.Values.Any(value => value == 0) ||
            values.Values.Distinct().Count() != values.Count)
        {
            throw new InvalidDataException(
                $"{name} values must be positive and unique.");
        }
    }

    private static string Normalize(string value) =>
        value.Replace("\r\n", "\n").TrimEnd() + "\n";
}
